title: Olivia Simauw
logo: assets/baker.jpg
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal

# Baker

## Education
Food Science, PhD

## Work Experience
Baker @ Chungyo Bread Store
- make 15 batch of bread every day
- cookies and cake

### Projects
- Catering kids brithday party
- 150 cookies for company event
